on: push
jobs:
  test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@master
    - name: Set XCode Version
      run: sudo xcode-select -s /Applications/Xcode.app
    - name: Install Dependencies
      run: |
        cd /Users/jackywong/Documents/Projects/MiniLives/TinyLives
        pod update
        pod install
      shell: bash
    - uses: ty0x2333/cocoapods-action@master
      with:
        additional_build_params: -destination 'platform=iOS Simulator,id=74FFFF0D-BD6F-449C-AB78-1BA33B6D0542'
        additional_lint_params: --private
